backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    sort_fields: ["date", "title"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Summary", name: "summary", widget: "text", pattern: [".{0,160}", "Keep the summary under 160 characters."] }
      - { label: "Body", name: "body", widget: "markdown" }
